### ISSUE TITLE
Dados desatualizados

### ISSUE THREAD

**Issue by sillasgonzaga** [culturagovbr/PDA-Sistema-MinC#1]
Primeiramente, parabéns pelo lançamento do portal de Dados Abertos. É uma excelente iniciativa.

Contudo, ao analisar o dataset de consumo de vale cultura, fiquei desapontado ao ver que,  traz dados de 02/2014 a 03/2015.

Existe um plano de acrescentar dados mais recentes aos datasets postados no portal?

**Comment by nitaibezerra** [comment]
Olá, Sillas,

Este repositório é do Plano de Dados Abertos - PDA, o documento publicado em http://plano.dados.cultura.gov.br/. As interações aqui (issues, PRs, etc) devem ser relativas ao documento do Plano em si.

Para solicitar dados, e/ou esclarecimentos sobre algum dado, recomendo que utilize os canais de [acesso à informação](http://www.acessoainformacao.gov.br/) ou [ouvidoria](http://ouvidoria.cultura.gov.br/). 

A organização no Github é de utilização para o desenvolvimento dos sistemas. A ideia de versionar o PDA em Markdown aqui visa abrir e transparecer o processo de planejamento, além de facilitar a edição do documento. Todavia não formaliza um canal de solicitação de informação sobre os dados. Um dia chegaremos lá..

Em relação ao Vale-Cultura o plano traz uma ação específica http://plano.dados.cultura.gov.br/#ação-03---abertura-de-dados-do-vale-cultura
